kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: mynamespace
subjects:
- kind: User
  name: system:anonymous 
  apiGroup: ""
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
